import type { AnalysisReport } from "../api/types";
import { buildExportDocument, type Block, type ExportDocument } from "./document";

// ---- Markdown ----------------------------------------------------------------------------

/** Escape text so repository-derived content cannot inject Markdown/HTML structure. */
export function escapeMarkdown(text: string): string {
  return text
    .replace(/\r?\n/g, " ")
    .replace(/([\\`*_{}[\]<>|#])/g, "\\$1");
}

function mdBlock(block: Block): string {
  switch (block.kind) {
    case "heading":
      return `${"#".repeat(block.level)} ${escapeMarkdown(block.text)}`;
    case "paragraph":
      return escapeMarkdown(block.text);
    case "note":
      return `> ${escapeMarkdown(block.text)}`;
    case "list":
      return block.items.map((i) => `- ${escapeMarkdown(i)}`).join("\n");
    case "table": {
      const align = block.headers.map((_, i) => (block.align?.[i] === "right" ? "---:" : "---"));
      const row = (cells: string[]) => `| ${cells.map((c) => escapeMarkdown(c) || " ").join(" | ")} |`;
      return [row(block.headers), `| ${align.join(" | ")} |`, ...block.rows.map(row)].join("\n");
    }
  }
}

export function renderMarkdown(doc: ExportDocument): string {
  return [`# ${escapeMarkdown(doc.title)}`, `_${escapeMarkdown(doc.subtitle)}_`, ...doc.blocks.map(mdBlock)].join("\n\n") + "\n";
}

// ---- HTML ----------------------------------------------------------------------------------

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function htmlBlock(block: Block): string {
  switch (block.kind) {
    case "heading":
      return `<h${block.level}>${escapeHtml(block.text)}</h${block.level}>`;
    case "paragraph":
      return `<p>${escapeHtml(block.text)}</p>`;
    case "note":
      return `<p class="note">${escapeHtml(block.text)}</p>`;
    case "list":
      return `<ul>${block.items.map((i) => `<li>${escapeHtml(i)}</li>`).join("")}</ul>`;
    case "table": {
      const cls = (i: number) => (block.align?.[i] === "right" ? ' class="num"' : "");
      const head = block.headers.map((h, i) => `<th${cls(i)}>${escapeHtml(h)}</th>`).join("");
      const body = block.rows
        .map((r) => `<tr>${r.map((c, i) => `<td${cls(i)}>${escapeHtml(c)}</td>`).join("")}</tr>`)
        .join("");
      return `<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
    }
  }
}

const STYLE = `
:root{color-scheme:light dark;--fg:#18181b;--muted:#71717a;--border:#e4e4e7;--bg:#fff;--subtle:#f4f4f5}
@media (prefers-color-scheme:dark){:root{--fg:#f4f4f5;--muted:#a1a1aa;--border:#27272a;--bg:#09090b;--subtle:#18181b}}
body{font:14px/1.55 ui-sans-serif,system-ui,sans-serif;color:var(--fg);background:var(--bg);max-width:980px;margin:32px auto;padding:0 16px}
h1{font-size:24px;margin:0}h2{font-size:18px;margin:32px 0 8px;padding-bottom:4px;border-bottom:1px solid var(--border)}h3{font-size:14px;margin:20px 0 6px}
.sub{color:var(--muted);margin:4px 0 24px}.note{color:var(--muted);font-size:12px;background:var(--subtle);padding:8px 10px;border-radius:6px}
table{border-collapse:collapse;width:100%;margin:8px 0;font-size:13px}th,td{border-bottom:1px solid var(--border);padding:4px 8px;text-align:left;vertical-align:top;overflow-wrap:anywhere}
th{color:var(--muted);font-weight:600}.num{text-align:right;font-variant-numeric:tabular-nums}
footer{margin-top:40px;color:var(--muted);font-size:12px}`;

export function renderHtml(doc: ExportDocument): string {
  return [
    "<!doctype html>",
    '<html lang="en"><head><meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1">',
    // The export is static: forbid scripts and remote resources entirely.
    `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'">`,
    `<title>${escapeHtml(doc.title)}</title><style>${STYLE}</style></head><body>`,
    `<h1>${escapeHtml(doc.title)}</h1><p class="sub">${escapeHtml(doc.subtitle)}</p>`,
    ...doc.blocks.map(htmlBlock),
    "<footer>Generated by RepoLens from deterministic static analysis. Security indicators are potential concerns, not confirmed vulnerabilities.</footer>",
    "</body></html>",
  ].join("\n");
}

// ---- Download -----------------------------------------------------------------------------

export type ExportFormat = "json" | "markdown" | "html";

export function exportReport(report: AnalysisReport, format: ExportFormat): { filename: string; mime: string; content: string } {
  const base = `repolens-${report.repository.full_name.replace("/", "-")}-${report.analysis.commit_sha.slice(0, 7)}`;
  if (format === "json") {
    return { filename: `${base}.json`, mime: "application/json", content: JSON.stringify(report, null, 2) };
  }
  const doc = buildExportDocument(report);
  if (format === "markdown") {
    return { filename: `${base}.md`, mime: "text/markdown", content: renderMarkdown(doc) };
  }
  return { filename: `${base}.html`, mime: "text/html", content: renderHtml(doc) };
}

export function downloadFile(filename: string, mime: string, content: string): void {
  const url = URL.createObjectURL(new Blob([content], { type: `${mime};charset=utf-8` }));
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
