import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { AISummaryPanel } from "@/components/dashboard/ai-summary-panel";

const SUMMARY = {
  purpose: "A demo FastAPI service.",
  architecture: "shop/api calls shop/services.",
  key_modules: [{ path: "shop/services", description: "User lookups." }],
  entry_points: ["shop/cli.py"],
  maintenance_concerns: ["Pin the Docker base image."],
  onboarding_steps: ["Run pytest"],
  provider: "anthropic",
  model: "claude-opus-5",
  commit_sha: "abc1234def",
  generated_at: "2026-09-18T00:00:00Z",
  disclaimer: "Generated by an AI model from RepoLens's deterministic analysis.",
};

function mockFetch(routes: Record<string, () => Response>) {
  return vi.fn(async (url: string) => routes[url]()) as unknown as typeof fetch;
}

describe("AISummaryPanel", () => {
  it("explains that AI is optional when the instance has no provider", async () => {
    const fetchImpl = mockFetch({
      "/api/health": () => Response.json({ ai_enabled: false, ai: { enabled: false } }),
    });
    render(<AISummaryPanel repositoryUrl="https://github.com/octo/demo" fetchImpl={fetchImpl} />);
    expect(await screen.findByText(/AI summaries are not enabled/)).toBeInTheDocument();
    expect(screen.queryByRole("button")).not.toBeInTheDocument();
  });

  it("generates a labelled summary on demand", async () => {
    const fetchImpl = mockFetch({
      "/api/health": () => Response.json({ ai: { enabled: true, provider: "anthropic", model: "claude-opus-5" } }),
      "/api/ai-summary": () => Response.json(SUMMARY),
    });
    render(<AISummaryPanel repositoryUrl="https://github.com/octo/demo" fetchImpl={fetchImpl} />);
    await userEvent.click(await screen.findByRole("button", { name: /Generate summary/ }));
    expect(await screen.findByText("A demo FastAPI service.")).toBeInTheDocument();
    expect(screen.getByRole("note")).toHaveTextContent("Generated by an AI model");
    expect(screen.getByText("shop/services")).toBeInTheDocument();
    expect(screen.getByText(/optional · AI-generated/)).toBeInTheDocument();
  });

  it("shows provider errors and allows retry", async () => {
    const fetchImpl = mockFetch({
      "/api/health": () => Response.json({ ai: { enabled: true, provider: "openai", model: "llama3.2" } }),
      "/api/ai-summary": () =>
        Response.json({ error: { code: "ai_unavailable", message: "The AI provider is rate limiting requests." } }, { status: 503 }),
    });
    render(<AISummaryPanel repositoryUrl="https://github.com/octo/demo" fetchImpl={fetchImpl} />);
    await userEvent.click(await screen.findByRole("button", { name: /Generate summary/ }));
    expect(await screen.findByRole("alert")).toHaveTextContent("rate limiting");
    expect(screen.getByRole("button", { name: /Try again/ })).toBeInTheDocument();
  });
});
