/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ai/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ai Summary
         * @description Optional AI narrative built from the deterministic report (never from raw code).
         *
         *     Returns 503 `ai_unavailable` when no provider is configured.
         */
        post: operations["ai_summary_api_ai_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Analyze a public repository and return the complete report.
         */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Stream
         * @description Same as /analyze, but streams progress events so clients can show the current stage.
         *
         *     Each line is one JSON object:
         *       {"type": "progress", "stage": "tree", "message": "..."}
         *       {"type": "result", "report": {...}}
         *       {"type": "error", "error": {"code": "...", "message": "...", "details": {...}}}
         */
        post: operations["analyze_stream_api_analyze_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{owner}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repository Metadata */
        get: operations["repository_metadata_api_repositories__owner___name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIStatus */
        AIStatus: {
            /** Enabled */
            enabled: boolean;
            /** Model */
            model?: string | null;
            /** Provider */
            provider?: string | null;
        };
        /** AISummary */
        AISummary: {
            /** Architecture */
            architecture: string;
            /** Commit Sha */
            commit_sha: string;
            /** Disclaimer */
            disclaimer: string;
            /** Entry Points */
            entry_points: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Key Modules */
            key_modules: components["schemas"]["KeyModule"][];
            /** Maintenance Concerns */
            maintenance_concerns: string[];
            /** Model */
            model: string;
            /** Onboarding Steps */
            onboarding_steps: string[];
            /** Provider */
            provider: string;
            /** Purpose */
            purpose: string;
        };
        /** AnalysisLimits */
        AnalysisLimits: {
            /** Max File Bytes */
            max_file_bytes: number;
            /** Max Files To Fetch */
            max_files_to_fetch: number;
            /** Max Total Fetch Bytes */
            max_total_fetch_bytes: number;
            /** Max Tree Entries */
            max_tree_entries: number;
        };
        /** AnalysisMeta */
        AnalysisMeta: {
            /**
             * Analyzed At
             * Format: date-time
             */
            analyzed_at: string;
            /** Commit Sha */
            commit_sha: string;
            /** Duration Ms */
            duration_ms: number;
            /** Engine Version */
            engine_version: string;
            fetch: components["schemas"]["FetchSummary"];
            /** Github Api Calls */
            github_api_calls: number;
            /** Head Commit Date */
            head_commit_date: string | null;
            limits: components["schemas"]["AnalysisLimits"];
            /** Notes */
            notes: string[];
            /** Partial */
            partial: boolean;
            rate_limit: components["schemas"]["RateLimitInfo"];
        };
        /** AnalysisReport */
        AnalysisReport: {
            analysis: components["schemas"]["AnalysisMeta"];
            architecture: components["schemas"]["ArchitectureAnalysis"];
            dependencies: components["schemas"]["DependencyAnalysis"];
            documentation: components["schemas"]["DocumentationAnalysis"];
            health: components["schemas"]["HealthReport"];
            languages: components["schemas"]["LanguageAnalysis"];
            quality: components["schemas"]["QualityAnalysis"];
            repository: components["schemas"]["RepositoryMetadata"];
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            security: components["schemas"]["SecurityAnalysis"];
            structure: components["schemas"]["StructureAnalysis"];
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Repository Url
             * @example https://github.com/psf/requests
             */
            repository_url: string;
        };
        /** ArchitectureAnalysis */
        ArchitectureAnalysis: {
            /** Compose Services */
            compose_services: components["schemas"]["ComposeService"][];
            /** Edges */
            edges: components["schemas"]["ModuleEdge"][];
            /** Entry Points */
            entry_points: components["schemas"]["EntryPoint"][];
            /** Frameworks */
            frameworks: components["schemas"]["Detection"][];
            /** Hubs */
            hubs: components["schemas"]["FileHub"][];
            import_resolution: components["schemas"]["ImportResolution"];
            /** Infrastructure */
            infrastructure: components["schemas"]["InfraItem"][];
            /** Methodology */
            methodology: string;
            /** Modules */
            modules: components["schemas"]["Module"][];
            /** Monorepo Tool */
            monorepo_tool: string | null;
            /** Notes */
            notes: string[];
            /** Project Types */
            project_types: components["schemas"]["Detection"][];
            /** Workspace Packages */
            workspace_packages: string[];
        };
        /** CategoryStat */
        CategoryStat: {
            /** Bytes */
            bytes: number;
            /** Category */
            category: string;
            /** Files */
            files: number;
        };
        /** CommentedCodeFile */
        CommentedCodeFile: {
            /** Lines */
            lines: number;
            /** Path */
            path: string;
        };
        /** ComplexityItem */
        ComplexityItem: {
            /** Complexity */
            complexity: number;
            /** Length */
            length: number;
            /** Line */
            line: number | null;
            /** Max Nesting */
            max_nesting?: number | null;
            /**
             * Method
             * @enum {string}
             */
            method: "python-ast" | "heuristic";
            /** Name */
            name: string | null;
            /** Path */
            path: string;
        };
        /** ComposeService */
        ComposeService: {
            /**
             * Build
             * @default false
             */
            build: boolean;
            /**
             * Depends On
             * @default []
             */
            depends_on: string[];
            /** Image */
            image?: string | null;
            /** Name */
            name: string;
        };
        /** Dependency */
        Dependency: {
            /**
             * Constraint
             * @enum {string}
             */
            constraint: "exact" | "range" | "none" | "managed" | "external";
            /**
             * Direct
             * @default true
             */
            direct: boolean;
            /** Ecosystem */
            ecosystem: string;
            /** Manifest */
            manifest: string;
            /** Name */
            name: string;
            /** Scope */
            scope: string;
            /** Source */
            source: string;
            /** Version */
            version: string | null;
        };
        /** DependencyAnalysis */
        DependencyAnalysis: {
            /** Dependencies */
            dependencies: components["schemas"]["Dependency"][];
            /** Dependencies Truncated */
            dependencies_truncated: boolean;
            /** Development */
            development: number;
            /** Ecosystems */
            ecosystems: components["schemas"]["EcosystemSummary"][];
            /** External Sources */
            external_sources: number;
            /** Lockfiles */
            lockfiles: string[];
            /** Manifests */
            manifests: components["schemas"]["ManifestSummary"][];
            /** Manifests Not Analyzed */
            manifests_not_analyzed: string[];
            /** Notes */
            notes: string[];
            /** Other */
            other: number;
            /** Production */
            production: number;
            /** Total */
            total: number;
            /** Unconstrained */
            unconstrained: number;
            /** Unique Packages */
            unique_packages: number;
            /** Version Conflicts */
            version_conflicts: components["schemas"]["VersionConflict"][];
            /** Vulnerability Data */
            vulnerability_data: string;
        };
        /** Detection */
        Detection: {
            /** Category */
            category: string;
            /** Evidence */
            evidence: string;
            /** Name */
            name: string;
        };
        /** DirectoryInfo */
        DirectoryInfo: {
            /**
             * Doc Files
             * @default 0
             */
            doc_files: number;
            /** Files */
            files: number;
            /** Path */
            path: string;
            /** Site Generator */
            site_generator?: string | null;
        };
        /** DirectoryStat */
        DirectoryStat: {
            /** Bytes */
            bytes: number;
            /** Files */
            files: number;
            /** Path */
            path: string;
        };
        /** DocstringCoverage */
        DocstringCoverage: {
            /** Documented */
            documented: number;
            /** Files Analyzed */
            files_analyzed: number;
            /** Percent */
            percent: number;
            /** Public Definitions */
            public_definitions: number;
        };
        /** DocumentationAnalysis */
        DocumentationAnalysis: {
            /** Comment Density */
            comment_density: number | null;
            docs_directory: components["schemas"]["DirectoryInfo"] | null;
            examples_directory: components["schemas"]["DirectoryInfo"] | null;
            /** Files */
            files: components["schemas"]["PresenceCheck"][];
            /** License File */
            license_file: string | null;
            /** License Name */
            license_name: string | null;
            /** License Spdx */
            license_spdx: string | null;
            /** Notes */
            notes: string[];
            python_docstrings: components["schemas"]["DocstringCoverage"] | null;
            readme: components["schemas"]["ReadmeInfo"] | null;
        };
        /** EcosystemSummary */
        EcosystemSummary: {
            /** Dependencies */
            dependencies: number;
            /** Development */
            development: number;
            /** Ecosystem */
            ecosystem: string;
            /** Has Lockfile */
            has_lockfile: boolean;
            /** Production */
            production: number;
        };
        /** EntryPoint */
        EntryPoint: {
            /** Evidence */
            evidence: string;
            /** Kind */
            kind: string;
            /** Path */
            path: string;
        };
        /** ExtensionStat */
        ExtensionStat: {
            /** Bytes */
            bytes: number;
            /** Extension */
            extension: string;
            /** Files */
            files: number;
        };
        /** FetchSummary */
        FetchSummary: {
            /** Budget Exhausted */
            budget_exhausted: boolean;
            /** Bytes Downloaded */
            bytes_downloaded: number;
            /** Failed */
            failed: number;
            /** Files Downloaded */
            files_downloaded: number;
            /** Files Selected */
            files_selected: number;
            /** Raw Rate Limited */
            raw_rate_limited: boolean;
            /** Skipped Binary */
            skipped_binary: number;
            /** Skipped Too Large */
            skipped_too_large: number;
        };
        /** FileHub */
        FileHub: {
            /** Imported By */
            imported_by: number;
            /** Path */
            path: string;
        };
        /** FileStat */
        FileStat: {
            /** Category */
            category: string;
            /** Language */
            language?: string | null;
            /** Path */
            path: string;
            /** Size */
            size: number;
        };
        /**
         * GitHubLanguageShare
         * @description Byte counts from GitHub's linguist-based /languages endpoint.
         */
        GitHubLanguageShare: {
            /** Bytes */
            bytes: number;
            /** Language */
            language: string;
            /** Percent */
            percent: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Max Points */
            max_points: number;
            /** Passed */
            passed: boolean;
            /** Points */
            points: number;
        };
        /** HealthDimension */
        HealthDimension: {
            /** Applicable */
            applicable: boolean;
            /** Checks */
            checks: components["schemas"]["HealthCheck"][];
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Score */
            score: number | null;
            /** Summary */
            summary: string;
        };
        /** HealthReport */
        HealthReport: {
            /** Dimensions */
            dimensions: components["schemas"]["HealthDimension"][];
            /** Methodology */
            methodology: string;
            /** Overall */
            overall: number | null;
        };
        /** HealthResponse */
        HealthResponse: {
            ai: components["schemas"]["AIStatus"];
            /** Ai Enabled */
            ai_enabled: boolean;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HygieneCheck */
        HygieneCheck: {
            /** Detail */
            detail: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Passed */
            passed: boolean;
        };
        /** ImportResolution */
        ImportResolution: {
            /** External */
            external: number;
            /** Files Parsed */
            files_parsed: number;
            /** Imports Found */
            imports_found: number;
            /** Internal Resolved */
            internal_resolved: number;
            /** Languages */
            languages: string[];
            /** Unresolved */
            unresolved: number;
        };
        /** InfraItem */
        InfraItem: {
            /** Detail */
            detail: string;
            /** Kind */
            kind: string;
            /** Path */
            path: string;
        };
        /** KeyModule */
        KeyModule: {
            /** Description */
            description: string;
            /** Path */
            path: string;
        };
        /** LanguageAnalysis */
        LanguageAnalysis: {
            /** Counted Lines */
            counted_lines: number;
            /** Estimated Lines */
            estimated_lines: number;
            /** Extensions */
            extensions: components["schemas"]["ExtensionStat"][];
            /** Github Breakdown */
            github_breakdown: components["schemas"]["GitHubLanguageShare"][];
            /** Languages */
            languages: components["schemas"]["LanguageStat"][];
            /** Methodology */
            methodology: string;
            /** Primary Language */
            primary_language: string | null;
            /** Sampled Files */
            sampled_files: number;
            /** Total Lines */
            total_lines: number;
        };
        /**
         * LanguageStat
         * @description Per-language statistics computed by RepoLens from the file tree.
         */
        LanguageStat: {
            /** Blank Lines */
            blank_lines: number;
            /** Bytes */
            bytes: number;
            /** Code Lines */
            code_lines: number;
            /** Comment Lines */
            comment_lines: number;
            /** Files */
            files: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "programming" | "markup" | "data" | "prose";
            /** Language */
            language: string;
            /** Lines */
            lines: number;
            /** Lines Estimated */
            lines_estimated: boolean;
            /** Percent Of Bytes */
            percent_of_bytes: number;
            /** Sampled Files */
            sampled_files: number;
        };
        /** LongFile */
        LongFile: {
            /** Estimated */
            estimated: boolean;
            /** Lines */
            lines: number;
            /** Path */
            path: string;
        };
        /** ManifestSummary */
        ManifestSummary: {
            /** Dependencies */
            dependencies: number;
            /** Ecosystem */
            ecosystem: string;
            /** Parse Error */
            parse_error?: string | null;
            /** Path */
            path: string;
        };
        /** MarkerItem */
        MarkerItem: {
            /** Line */
            line: number;
            /** Path */
            path: string;
            /** Tag */
            tag: string;
            /** Text */
            text: string;
        };
        /** Module */
        Module: {
            /** Bytes */
            bytes: number;
            /** Files */
            files: number;
            /** Id */
            id: string;
            /** Languages */
            languages: string[];
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Role */
            role: string;
            /** Role Source */
            role_source: string;
            /** Sampled Files */
            sampled_files: number;
            /** Source Files */
            source_files: number;
        };
        /** ModuleEdge */
        ModuleEdge: {
            /** Imports */
            imports: number;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** PresenceCheck */
        PresenceCheck: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Path */
            path?: string | null;
            /** Present */
            present: boolean;
        };
        /** QualityAnalysis */
        QualityAnalysis: {
            /** Average Lines Per Sampled File */
            average_lines_per_sampled_file: number | null;
            /** Average Source File Bytes */
            average_source_file_bytes: number;
            /** Commented Code Files */
            commented_code_files: components["schemas"]["CommentedCodeFile"][];
            /** Commented Code Lines */
            commented_code_lines: number;
            /** Complexity Hotspots */
            complexity_hotspots: components["schemas"]["ComplexityItem"][];
            /** Complexity Threshold */
            complexity_threshold: number;
            /** Coverage Note */
            coverage_note: string;
            /** High Complexity Count */
            high_complexity_count: number;
            /** Largest Source Files */
            largest_source_files: components["schemas"]["LongFile"][];
            /** Long File Count */
            long_file_count: number;
            /** Long File Threshold */
            long_file_threshold: number;
            /** Long Files */
            long_files: components["schemas"]["LongFile"][];
            /** Marker Counts */
            marker_counts: {
                [key: string]: number;
            };
            /** Markers */
            markers: components["schemas"]["MarkerItem"][];
            /** Markers Truncated */
            markers_truncated: boolean;
            /** Methodology */
            methodology: string;
            /** Python Functions Analyzed */
            python_functions_analyzed: number;
            /** Sampled Source Files */
            sampled_source_files: number;
            /** Source Bytes */
            source_bytes: number;
            /** Source Files */
            source_files: number;
            /** Test Files */
            test_files: number;
            /** Test To Source Ratio */
            test_to_source_ratio: number | null;
            tooling: components["schemas"]["Tooling"];
        };
        /** RateLimitInfo */
        RateLimitInfo: {
            /**
             * Authenticated
             * @default false
             */
            authenticated: boolean;
            /** Limit */
            limit?: number | null;
            /** Remaining */
            remaining?: number | null;
            /** Reset At */
            reset_at?: string | null;
        };
        /** ReadmeInfo */
        ReadmeInfo: {
            /** Badges */
            badges: number;
            /** Broken Relative Links */
            broken_relative_links: string[];
            /** Bytes */
            bytes: number;
            /** Code Blocks */
            code_blocks: number;
            /** Format */
            format: string;
            /** Has Table Of Contents */
            has_table_of_contents: boolean;
            /** Headings */
            headings: string[];
            /** Images */
            images: number;
            /** Lines */
            lines: number;
            /** Links */
            links: number;
            /** Path */
            path: string;
            /** Reading Minutes */
            reading_minutes: number;
            /** Sections */
            sections: components["schemas"]["PresenceCheck"][];
            /** Words */
            words: number;
        };
        /**
         * RepositoryMetadata
         * @description Repository facts exactly as reported by the GitHub REST API.
         */
        RepositoryMetadata: {
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /** Created At */
            created_at?: string | null;
            /** Default Branch */
            default_branch: string;
            /** Description */
            description?: string | null;
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
            /** Forks */
            forks: number;
            /** Full Name */
            full_name: string;
            /** Homepage */
            homepage?: string | null;
            /** Html Url */
            html_url: string;
            /**
             * Is Fork
             * @default false
             */
            is_fork: boolean;
            /**
             * Is Template
             * @default false
             */
            is_template: boolean;
            /** License Name */
            license_name?: string | null;
            /** License Spdx */
            license_spdx?: string | null;
            /** Name */
            name: string;
            /** Open Issues */
            open_issues: number;
            /** Owner */
            owner: string;
            /** Owner Avatar Url */
            owner_avatar_url?: string | null;
            /** Owner Type */
            owner_type?: string | null;
            /** Primary Language */
            primary_language?: string | null;
            /** Pushed At */
            pushed_at?: string | null;
            /** Size Kb */
            size_kb: number;
            /** Stars */
            stars: number;
            /**
             * Topics
             * @default []
             */
            topics: string[];
            /** Updated At */
            updated_at?: string | null;
            /** Watchers */
            watchers: number;
        };
        /** SecurityAnalysis */
        SecurityAnalysis: {
            /** Counts By Category */
            counts_by_category: {
                [key: string]: number;
            };
            /** Counts By Severity */
            counts_by_severity: {
                [key: string]: number;
            };
            /** Coverage Note */
            coverage_note: string;
            /** Disclaimer */
            disclaimer: string;
            /** Env Variable Files */
            env_variable_files: number;
            /** Env Variables */
            env_variables: string[];
            /** Files Scanned */
            files_scanned: number;
            /** Findings */
            findings: components["schemas"]["SecurityFinding"][];
            /** Findings Truncated */
            findings_truncated: boolean;
            /** Hygiene */
            hygiene: components["schemas"]["HygieneCheck"][];
            /** Rules */
            rules: components["schemas"]["SecurityRule"][];
        };
        /** SecurityFinding */
        SecurityFinding: {
            /** Category */
            category: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Description */
            description: string;
            /** Evidence */
            evidence?: string | null;
            /**
             * In Test
             * @default false
             */
            in_test: boolean;
            /** Line */
            line?: number | null;
            /** Path */
            path: string;
            /** Rule */
            rule: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "high" | "medium" | "low" | "info";
            /** Title */
            title: string;
        };
        /** SecurityRule */
        SecurityRule: {
            /** Category */
            category: string;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "high" | "medium" | "low" | "info";
            /** Title */
            title: string;
        };
        /** StructureAnalysis */
        StructureAnalysis: {
            /** Analyzed Files */
            analyzed_files: number;
            /** Analyzed Size Bytes */
            analyzed_size_bytes: number;
            /** Categories */
            categories: components["schemas"]["CategoryStat"][];
            /** Ignored Directories */
            ignored_directories: components["schemas"]["DirectoryStat"][];
            /** Ignored Files */
            ignored_files: number;
            /** Ignored Size Bytes */
            ignored_size_bytes: number;
            /** Largest Directories */
            largest_directories: components["schemas"]["DirectoryStat"][];
            /** Largest Files */
            largest_files: components["schemas"]["FileStat"][];
            /** Max Depth */
            max_depth: number;
            /** Notes */
            notes: string[];
            /** Oversized Files */
            oversized_files: number;
            /** Product Max Depth */
            product_max_depth: number;
            /** Submodules */
            submodules: string[];
            /** Symlinks */
            symlinks: number;
            /** Top Level */
            top_level: components["schemas"]["TreeNode"][];
            /** Total Directories */
            total_directories: number;
            /** Total Files */
            total_files: number;
            /** Total Size Bytes */
            total_size_bytes: number;
            tree: components["schemas"]["TreeNode"];
            /** Tree Node Budget */
            tree_node_budget: number;
            /** Truncated */
            truncated: boolean;
        };
        /** Tooling */
        Tooling: {
            /** Ci */
            ci: string[];
            /** Editorconfig */
            editorconfig: boolean;
            /** Formatters */
            formatters: string[];
            /** Linters */
            linters: string[];
            /** Pre Commit */
            pre_commit: boolean;
            /** Test Frameworks */
            test_frameworks: string[];
            /** Type Checkers */
            type_checkers: string[];
        };
        /** TreeNode */
        TreeNode: {
            /** Children */
            children?: components["schemas"]["TreeNode"][] | null;
            /**
             * Files
             * @default 0
             */
            files: number;
            /**
             * Ignored
             * @default false
             */
            ignored: boolean;
            /** Name */
            name: string;
            /**
             * Omitted Children
             * @default 0
             */
            omitted_children: number;
            /** Path */
            path: string;
            /**
             * Size
             * @default 0
             */
            size: number;
            /**
             * Type
             * @enum {string}
             */
            type: "dir" | "file" | "symlink" | "submodule";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionConflict */
        VersionConflict: {
            /** Ecosystem */
            ecosystem: string;
            /** Manifests */
            manifests: string[];
            /** Name */
            name: string;
            /** Versions */
            versions: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ai_summary_api_ai_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_stream_api_analyze_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Newline-delimited JSON events: progress, then result or error. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    repository_metadata_api_repositories__owner___name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
